spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.us3vvyu.mongodb.net/Cluster0
cloud:
  aws:
    stack:
      auto: false
    region:
      static: eu-west-2
    credentials:
      access-key: AKIAZWTXQ7KCJRSXXEOD
      secret-key: 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
